# TASK 1

1 Write a function to compute 5/0 and use try/except to catch the exceptions.

In [18]:
def division(a, b):
    try:
        return a/b
    except ZeroDivisionError:
        print("Error: Divide by zero is not defined")
        
#example
division(5,0)

Error: Divide by zero is not defined


2 Implement a Python program to generate all sentences where subject is in
["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in
<br>
["Baseball","cricket"].<br>
Hint: Subject,Verb and Object should be declared in the program as shown below.<br>
subjects=["Americans ","Indians"]<br>
verbs=["play","watch"]<br>
objects=["Baseball","Cricket"]<br>
<br>
<b>Output should come as below:</b><br>
Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.<br>

In [19]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for subject in subjects:
    for verb in verbs:
        for object in objects:
            print(subject,verb,object)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# TASK 2

1.
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [5]:
import numpy as np

In [6]:
def vandermonde_matrix(myvector, n, increasing=False):
    
    if not increasing:
        out=[]
        for x in myvector:
            for i in range(n):
                out.append(x**(n-1-i))
        matrix=np.array(out).reshape(myvector.size,n)
    else:
        out=[]
        for x in myvector:
            for i in range(n):
                out.append(x**i)
        matrix=np.array(out).reshape(myvector.size,n)
    
    return matrix   

In [16]:
vector=np.array([2,3,4,5])
columns_num=5
print('This is decreasing Vandermonde Matrix\n')
print(vandermonde_matrix(vector,columns_num,False))
print('\nThis is increasing Vandermonde Matrix')
print(vandermonde_matrix(vector,columns_num,True))

This is decreasing Vandermonde Matrix

[[ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]

This is increasing Vandermonde Matrix
[[  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
